# time
months = {'01': 'january', '02': 'february', '03': 'march', '04': 'april', '05': 'may', '06': 'june', '07': 'july', '08': 'august', '09': 'september', '10': 'october', '11': 'november', '12': 'december'}
quarters = ['01', '02', '03', '04']

# geography
states = {'02': {'abbreviation': 'AK', 'name': 'ALASKA'}, '01': {'abbreviation': 'AL', 'name': 'ALABAMA'}, '05': {'abbreviation': 'AR', 'name': 'ARKANSAS'}, '60': {'abbreviation': 'AS', 'name': 'AMERICAN SAMOA'}, '04': {'abbreviation': 'AZ', 'name': 'ARIZONA'}, '06': {'abbreviation': 'CA', 'name': 'CALIFORNIA'}, '08': {'abbreviation': 'CO', 'name': 'COLORADO'}, '09': {'abbreviation': 'CT', 'name': 'CONNECTICUT'}, '11': {'abbreviation': 'DC', 'name': 'DISTRICT OF COLUMBIA'}, '10': {'abbreviation': 'DE', 'name': 'DELAWARE'}, '12': {'abbreviation': 'FL', 'name': 'FLORIDA'}, '13': {'abbreviation': 'GA', 'name': 'GEORGIA'}, '66': {'abbreviation': 'GU', 'name': 'GUAM'}, '15': {'abbreviation': 'HI', 'name': 'HAWAII'}, '19': {'abbreviation': 'IA', 'name': 'IOWA'}, '16': {'abbreviation': 'ID', 'name': 'IDAHO'}, '17': {'abbreviation': 'IL', 'name': 'ILLINOIS'}, '18': {'abbreviation': 'IN', 'name': 'INDIANA'}, '20': {'abbreviation': 'KS', 'name': 'KANSAS'}, '21': {'abbreviation': 'KY', 'name': 'KENTUCKY'}, '22': {'abbreviation': 'LA', 'name': 'LOUISIANA'}, '25': {'abbreviation': 'MA', 'name': 'MASSACHUSETTS'}, '24': {'abbreviation': 'MD', 'name': 'MARYLAND'}, '23': {'abbreviation': 'ME', 'name': 'MAINE'}, '26': {'abbreviation': 'MI', 'name': 'MICHIGAN'}, '27': {'abbreviation': 'MN', 'name': 'MINNESOTA'}, '29': {'abbreviation': 'MO', 'name': 'MISSOURI'}, '28': {'abbreviation': 'MS', 'name': 'MISSISSIPPI'}, '30': {'abbreviation': 'MT', 'name': 'MONTANA'}, '37': {'abbreviation': 'NC', 'name': 'NORTH CAROLINA'}, '38': {'abbreviation': 'ND', 'name': 'NORTH DAKOTA'}, '31': {'abbreviation': 'NE', 'name': 'NEBRASKA'}, '33': {'abbreviation': 'NH', 'name': 'NEW HAMPSHIRE'}, '34': {'abbreviation': 'NJ', 'name': 'NEW JERSEY'}, '35': {'abbreviation': 'NM', 'name': 'NEW MEXICO'}, '32': {'abbreviation': 'NV', 'name': 'NEVADA'}, '36': {'abbreviation': 'NY', 'name': 'NEW YORK'}, '39': {'abbreviation': 'OH', 'name': 'OHIO'}, '40': {'abbreviation': 'OK', 'name': 'OKLAHOMA'}, '41': {'abbreviation': 'OR', 'name': 'OREGON'}, '42': {'abbreviation': 'PA', 'name': 'PENNSYLVANIA'}, '72': {'abbreviation': 'PR', 'name': 'PUERTO RICO'}, '44': {'abbreviation': 'RI', 'name': 'RHODE ISLAND'}, '45': {'abbreviation': 'SC', 'name': 'SOUTH CAROLINA'}, '46': {'abbreviation': 'SD', 'name': 'SOUTH DAKOTA'}, '47': {'abbreviation': 'TN', 'name': 'TENNESSEE'}, '48': {'abbreviation': 'TX', 'name': 'TEXAS'}, '49': {'abbreviation': 'UT', 'name': 'UTAH'}, '51': {'abbreviation': 'VA', 'name': 'VIRGINIA'}, '78': {'abbreviation': 'VI', 'name': 'VIRGIN ISLANDS'}, '50': {'abbreviation': 'VT', 'name': 'VERMONT'}, '53': {'abbreviation': 'WA', 'name': 'WASHINGTON'}, '55': {'abbreviation': 'WI', 'name': 'WISCONSIN'}, '54': {'abbreviation': 'WV', 'name': 'WEST VIRGINIA'}, '56': {'abbreviation': 'WY', 'name': 'WYOMING'}}

# msha address/employment csv headers
ae_headers = ('year_file', 'update_date', 'mine_id', 'contractor', 'filler01', 'inspection_office', 'state_code', 'county_code', 'sic', 'filler02', 'canvass', 'mine_type', 'status_code', 'status_date', 'seam_height', 'filler03', 'prior_status_code', 'travel_area', 'mailing_control', 'company_name', 'filler04', 'mine_name', 'filler05', 'address', 'filler06', 'city', 'filler07', 'state_abbreviation', 'zip_code', 'filler08', 'county_name', 'injury_flag_q1', 'injury_count_q1', 'injury_flag_q2', 'injury_count_q2', 'injury_flag_q3', 'injury_count_q3', 'injury_flag_q4', 'injury_count_q4', 'work_group', 'update_addition_year', 'update_addition_number', 'update_change_year', 'update_change_number', 'number_subunits', 'subunit_1_code', 'subunit_1_document_number_q1', 'subunit_1_number_employees_q1', 'subunit_1_employee_hours_q1', 'subunit_1_tons_production_q1', 'subunit_1_document_number_q2', 'subunit_1_number_employees_q2', 'subunit_1_employee_hours_q2', 'subunit_1_tons_production_q2', 'subunit_1_document_number_q3', 'subunit_1_number_employees_q3', 'subunit_1_employee_hours_q3', 'subunit_1_tons_production_q3', 'subunit_1_document_number_q4', 'subunit_1_number_employees_q4', 'subunit_1_employee_hours_q4', 'subunit_1_tons_production_q4' 'subunit_2_code', 'subunit_2_document_number_q1', 'subunit_2_number_employees_q1', 'subunit_2_employee_hours_q1', 'subunit_2_tons_production_q1', 'subunit_2_document_number_q2', 'subunit_2_number_employees_q2', 'subunit_2_employee_hours_q2', 'subunit_2_tons_production_q2', 'subunit_2_document_number_q3', 'subunit_2_number_employees_q3', 'subunit_2_employee_hours_q3', 'subunit_2_tons_production_q3', 'subunit_2_document_number_q4', 'subunit_2_number_employees_q4', 'subunit_2_employee_hours_q4', 'subunit_2_tons_production_q4' 'subunit_3_code', 'subunit_3_document_number_q1', 'subunit_3_number_employees_q1', 'subunit_3_employee_hours_q1', 'subunit_3_tons_production_q1', 'subunit_3_document_number_q2', 'subunit_3_number_employees_q2', 'subunit_3_employee_hours_q2', 'subunit_3_tons_production_q2', 'subunit_3_document_number_q3', 'subunit_3_number_employees_q3', 'subunit_3_employee_hours_q3', 'subunit_3_tons_production_q3', 'subunit_3_document_number_q4', 'subunit_3_number_employees_q4', 'subunit_3_employee_hours_q4', 'subunit_3_tons_production_q4' 'subunit_4_code', 'subunit_4_document_number_q1', 'subunit_4_number_employees_q1', 'subunit_4_employee_hours_q1', 'subunit_4_tons_production_q1', 'subunit_4_document_number_q2', 'subunit_4_number_employees_q2', 'subunit_4_employee_hours_q2', 'subunit_4_tons_production_q2', 'subunit_4_document_number_q3', 'subunit_4_number_employees_q3', 'subunit_4_employee_hours_q3', 'subunit_4_tons_production_q3', 'subunit_4_document_number_q4', 'subunit_4_number_employees_q4', 'subunit_4_employee_hours_q4', 'subunit_4_tons_production_q4')



